name: Flutter Build
on:
   push:
      branches:
         - master
   pull_request:
     

jobs:
  build_ios:
    name: (iOS)
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any
      # matrix job fails.
      fail-fast: false
      matrix:
        api-level: [21,31] # [minSdk, most used, newest (30 is not working :(] 19 would be minSDK but does not support x86_64
        target: [default] # [default, google_apis]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.0'
    # - run: "flutter upgrade"
    - run: "flutter --version"
    - run: "flutter pub get"
    - run: "flutter build ios -t 'lib/main.dart' --debug --no-codesign"

  build_appbundle:
    name: (Android)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any
      # matrix job fails.
      fail-fast: false
      matrix:
        api-level: [ 24, 30, 34 ] # [minSdk, most used, newest]
        target: [ default ] # [default, google_apis]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0'
      # - run: "flutter upgrade"
      - run: "flutter --version"
      - run: "flutter pub get"
      - run: 'flutter clean'
      - run: "flutter build apk -t 'lib/main.dart' --debug --flavor edumfa"
